/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-15 06:44:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<title>W3.CSS Template</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/lib/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("body,h1 {font-family: \"Montserrat\", sans-serif}\r\n");
      out.write("img {margin-bottom: -7px}\r\n");
      out.write(".w3-row-padding img {margin-bottom: 12px}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Sidenav -->\r\n");
      out.write("<nav class=\"w3-sidenav w3-black w3-animate-top w3-center w3-xxlarge\" style=\"display:none;padding-top:150px\" id=\"mySidenav\">\r\n");
      out.write("  <a href=\"javascript:void(0)\" onclick=\"w3_close()\" class=\"w3-closenav w3-jumbo w3-display-topright\" style=\"padding:6px 24px\">\r\n");
      out.write("    <i class=\"fa fa-remove\"></i>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"w3-text-grey w3-hover-black\">About</a>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"w3-text-grey w3-hover-black\">Photos</a>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"w3-text-grey w3-hover-black\">Shop</a>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"w3-text-grey w3-hover-black\">Contact</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- !PAGE CONTENT! -->\r\n");
      out.write("<div class=\"w3-content\" style=\"max-width:1500px\">\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("<header class=\"w3-container w3-padding-32 w3-center w3-opacity w3-margin-bottom\">\r\n");
      out.write("  <span class=\"w3-opennav w3-xxlarge w3-right w3-margin-right\" onclick=\"w3_open()\"><i class=\"fa fa-bars\"></i></span> \r\n");
      out.write("  <div class=\"w3-clear\"></div>\r\n");
      out.write("  <h1><b>PHOTOLIO</b></h1>\r\n");
      out.write("  <p><b>A template made by w3.css for photographers.</b></p>\r\n");
      out.write("  <p class=\"w3-padding-16\"><button class=\"w3-btn\" onclick=\"myFunction()\">Toggle Grid Padding</button></p>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- Photo Grid -->\r\n");
      out.write("<div class=\"w3-row\" id=\"myGrid\" style=\"margin-bottom:128px\">\r\n");
      out.write("  <div class=\"w3-third\">\r\n");
      out.write("    <img src=\"/w3images/rocks.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/sound.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/woods.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/rock.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/nature.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/mist.jpg\" style=\"width:100%\">\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-third\">\r\n");
      out.write("    <img src=\"/w3images/coffee.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/bridge.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/notebook.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/london.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/rocks.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/avatar_g.jpg\" style=\"width:100%\">\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"w3-third\">\r\n");
      out.write("    <img src=\"/w3images/mist.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/workbench.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/gondol.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/skies.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/lights.jpg\" style=\"width:100%\">\r\n");
      out.write("    <img src=\"/w3images/workshop.jpg\" style=\"width:100%\">\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- End Page Content -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"w3-container w3-padding-64 w3-light-grey w3-center w3-opacity w3-xlarge\" style=\"margin-top:128px\"> \r\n");
      out.write("  <i class=\"fa fa-facebook-official w3-hover-text-indigo\"></i>\r\n");
      out.write("   <i class=\"fa fa-instagram w3-hover-text-purple\"></i>\r\n");
      out.write("  <i class=\"fa fa-snapchat w3-hover-text-yellow\"></i>\r\n");
      out.write("  <i class=\"fa fa-pinterest-p w3-hover-text-red\"></i>\r\n");
      out.write("  <i class=\"fa fa-twitter w3-hover-text-light-blue\"></i>\r\n");
      out.write("  <i class=\"fa fa-linkedin w3-hover-text-indigo\"></i>\r\n");
      out.write("  <p class=\"w3-medium\">Powered by <a href=\"http://www.w3schools.com/w3css/default.asp\" target=\"_blank\" class=\"w3-hover-text-green\">w3.css</a></p>\r\n");
      out.write("</footer>\r\n");
      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("// Toggle grid padding\r\n");
      out.write("function myFunction() {\r\n");
      out.write("    var x = document.getElementById(\"myGrid\");\r\n");
      out.write("    if (x.className === \"w3-row\") {\r\n");
      out.write("        x.className = \"w3-row-padding\";\r\n");
      out.write("    } else { \r\n");
      out.write("        x.className = x.className.replace(\"w3-row-padding\", \"w3-row\");\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Open and close sidenav\r\n");
      out.write("function w3_open() {\r\n");
      out.write("    document.getElementById(\"mySidenav\").style.width = \"100%\";\r\n");
      out.write("    document.getElementById(\"mySidenav\").style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function w3_close() {\r\n");
      out.write("    document.getElementById(\"mySidenav\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
