/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-27 11:24:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class j02_005fDomAttribute_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\"> <title>Insert title here</title>\r\n");
      out.write("  </head>ㅁㅁㅁㅁ\r\n");
      out.write("  <body>\r\n");
      out.write("\t<aaa><bbb>00000</bbb>11111\r\n");
      out.write("<!-- 꺽쇠 바깥부분이 #Text 이다!! -->\r\n");
      out.write("\t\t<bbb></bbb>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<bbb id=\"a\" msg=\"둘리\">22222</bbb>\r\n");
      out.write("\t\t<bbb id=\"b\" msg=\"마이콜\">33333</bbb>\r\n");
      out.write("\t\t<bbb id=\"b\" data=\"도우너\">44444</bbb>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<bbb id=\"c\" id=\"d\" id=\"e\" msg=\"희동이\">많은 아이디</bbb>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<bbb><ccc if=\"f\" mid=\"아아\">55555</ccc></bbb>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<bbb>\r\n");
      out.write("\t\t\t<ccc id=\"ff\" mid=\"가가\">66666</ccc>\r\n");
      out.write("\t\t</bbb>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<bbb value=\"cc\"></bbb>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</aaa>\r\n");
      out.write("\t\r\n");
      out.write("\t<aaa>\r\n");
      out.write("\t\t<bbb>AAAAAA</bbb>\r\n");
      out.write("\t\t<bbb id=\"g\">BBBBB</bbb>\r\n");
      out.write("\t</aaa>\r\n");
      out.write("\t\r\n");
      out.write("\t<aaa style=\"display: none\">메시지 XXXXX</aaa> <br>\r\n");
      out.write("\t\r\n");
      out.write("\t<aaa id=\"show\" style=\"display: \">메시지 OOOOO</aaa> <br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dixEx\" style=\"border: solid 1px black;\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t1. 루트노드(documentElement)\r\n");
      out.write("\t<input type=\"button\" value=\"루트태그이름\" onclick=\"root01()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction root01() {\r\n");
      out.write("\t\t\tvar root = document.documentElement;\r\n");
      out.write("\t\t\talert(\"root 태그 이름 : \" + root.tagName);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<input type=\"button\" value=\"루트태그의 ChildNode태그들\"\r\n");
      out.write("\t\t\tonclick=\"root02()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction root02() {\r\n");
      out.write("\t\t\tvar root = document.documentElement;\r\n");
      out.write("\t\t\talert(\"존재 여부 :\" + root.hasChildNodes());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar rootChildList = root.childNodes;\r\n");
      out.write("\t\t\talert(\"갯수 : \" + rootChildList.length);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\tfor(i=0; i<rootChildList.length; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tmsg += rootChildList.item(i).nodeName + \"\\n\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert(\"root태그의 Element List \\n\" + msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t2. body 노드\r\n");
      out.write("\t<input type=\"button\" value=\"body노드의 Child태그들(for이용)\"\r\n");
      out.write("\t\t\tonclick=\"body01()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction body01() {\r\n");
      out.write("\t\t\tvar root = document.documentElement;\r\n");
      out.write("\t\t\tvar rootChildList = root.childNodes;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(i=0; i<rootChildList.length; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(rootChildList.item(i).nodeName == \"BODY\") {\r\n");
      out.write("// \t\t\t\t\tif의 검색에서 사용되는 키워드는 대소문자를 구별함\r\n");
      out.write("\t\t\t\t\tvar bodyChildList = rootChildList.item(i).childNodes;\r\n");
      out.write("\t\t\t\t\talert(\"갯수 : \" + bodyChildList.length);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\t\t\tfor(k=0; k<bodyChildList.length; k++) {\r\n");
      out.write("\t\t\t\t\t\tmsg += bodyChildList.item(i).nodeName + \"\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\talert(\"bodyChild 목록 \\n\" + msg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\t\tvalue=\"body노드의 Child 태그들(ByTagName이용)\"\r\n");
      out.write("\t\t\tonclick=\"body02()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction body02() {\r\n");
      out.write("\t\t\tvar bodyEleList = \r\n");
      out.write("\t\t\t\tdocument.getElementsByTagName(\"body\");\r\n");
      out.write("\t\t\t\t\t\t\t\t// 이곳의 body는 대소문자 구분하지 않음\r\n");
      out.write("\t\t\talert(\"이름 : \" + bodyEleList.item(0).nodeName);\r\n");
      out.write("\t\t\tvar bodyChildList = \r\n");
      out.write("\t\t\t\tbodyEleList.item(0).childNodes;\r\n");
      out.write("\t\t\talert(\"갯수 : \" + bodyChildList.length);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\tfor(i=0; i<bodyChildList.length; i++) {\r\n");
      out.write("\t\t\t\tmsg += bodyChildList.item(i).nodeName + \"\\n\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert(\"bodyChildList 목록 \\n\" + msg)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t3. aaa Element의 노드\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\tvalue=\"aaa노드의 childNodes\"\r\n");
      out.write("\t\tonclick=\"aaa01()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction aaa01() {\r\n");
      out.write("\t\t\tvar aaaEleList =\r\n");
      out.write("\t\t\t\tdocument.getElementsByTagName(\"aaa\");\r\n");
      out.write("\t\t\tvar aaaFirstEle = aaaEleList.item(0);\r\n");
      out.write("\t\t\tvar aaaFChildList = aaaFirstEle.childNodes;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\tfor(p=0; p<aaaFChildList.length; p++) {\r\n");
      out.write("\t\t\t\tmsg +=\r\n");
      out.write("\t\t\t\t\tp + \"번째 노드\\n\" +\r\n");
      out.write("\t\t\t\t\t\"- 이름 : \" + aaaFChildList.item(p).nodeName + \"\\n\"+\r\n");
      out.write("\t\t\t\t\t\"- 값 : \" + aaaFChildList.item(p).nodeValue + \"\\n\"+\r\n");
      out.write("\t\t\t\t\t\"- 타입: \" + aaaFChildList.item(p).nodeType + \"\\n\\n\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert(\"첫번째 aaa노드의 ChildList 목록\\n\" + msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\t\tvalue=\"첫번쨰aaa노드의firstChild\"\r\n");
      out.write("\t\t\tonclick=\"aaa02()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction aaa02() {\r\n");
      out.write("\t\t\tvar aaaEleList = \r\n");
      out.write("\t\t\t\tdocument.getElementsByTagName(\"aaa\");\r\n");
      out.write("\t\t\tvar aaaFirsrtChild = aaaEleList.item(0).firstChild;\r\n");
      out.write("\t\t\tvar msg =\r\n");
      out.write("\t\t\t\t\"첫번째 aaa 노드의 firstChild노드 : \" +\r\n");
      out.write("\t\t\t\t\"이름 = \" + aaaFirsrtChild.nodeName + \"\\n\" + \r\n");
      out.write("\t\t\t\t\"값 = \" + aaaFirsrtChild.nodeValue + \"\\n\" + \r\n");
      out.write("\t\t\t\t\"타입 : \" + aaaFirsrtChild.nodeType;\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t4. bbb Element의 노드\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\t\tvalue=\"bbb태그들과 attribute\"\r\n");
      out.write("\t\t\tonclick=\"bbb01()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction bbb01() {\r\n");
      out.write("\t\t\tvar bbbEleList = document.getElementsByTagName(\"bbb\");\r\n");
      out.write("\t\t\talert(\"갯수 : \" + bbbEleList.length);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\tfor(t=0; t<bbbEleList.length; t++) {\r\n");
      out.write("\t\t\t\tmsg += t + \"번째 bbb \\n\" \r\n");
      out.write("\t\t\t\t\t+ \"- attribute 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ bbbEleList.item(t).hasAttributes() + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- nodeValue : \" \r\n");
      out.write("\t\t\t\t\t+ bbbEleList.item(t).nodeValue + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- childNodes 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ bbbEleList.item(t).hasChildNodes() + \"\\n\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(bbbEleList.item(t).hasChildNodes() == true) {\r\n");
      out.write("\t\t\t\t\t\tmsg += \"---- 첫번째 childNode의 nodeName : \"\r\n");
      out.write("\t\t\t\t\t\t\t+ bbbEleList.item(t).childNodes.item(0).nodeName \r\n");
      out.write("\t\t\t\t\t\t\t+ \"\\n\"\r\n");
      out.write("\t\t\t\t\t\t\t+ \"---- 첫번째 childNode의  nodeVlaue : \"\r\n");
      out.write("\t\t\t\t\t\t\t+ bbbEleList.item(t).childNodes.item(0).nodeValue\r\n");
      out.write("\t\t\t\t\t\t\t+ \"\\n\\n\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tmsg += \"\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert(\"bbbList 목록 \\n\" + msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t5. id이용 (중복 id는 불가)\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\t\tvalue=\"id가 a인 노드(ByID)\"\r\n");
      out.write("\t\t\tonclick=\"id01()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction id01() {\r\n");
      out.write("\t\t\tvar nodeId = document.getElementById(\"a\");\r\n");
      out.write("\t\t\tvar msg = \"- id attr 값 : \" \r\n");
      out.write("\t\t\t\t\t+ nodeId.getAttribute(\"id\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- msg attr 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.hasAttribute(\"msg\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- data attr 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.hasAttribute(\"data\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- msg attr 값 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.getAttribute(\"msg\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- 첫번째 childNode의 nodeName : \" \r\n");
      out.write("\t\t\t\t\t+ nodeId.childNodes.item(0).nodeName + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- 첫번쨰 childNode의 nodeValue : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.childNodes.item(0).nodeValue;\r\n");
      out.write("\t\t\t\talert(msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\t\tvalue=\"id가 b인 노드(ByID)\"\r\n");
      out.write("\t\t\tonclick=\"id02()\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction id02() {\r\n");
      out.write("\t\t\tvar nodeId = document.getElementById(\"b\");\r\n");
      out.write("\t\t\tvar msg = \"- id attr 값 : \" \r\n");
      out.write("\t\t\t\t\t+ nodeId.getAttribute(\"id\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- msg attr 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.hasAttribute(\"msg\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- data attr 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.hasAttribute(\"data\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- msg attr 값 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.getAttribute(\"msg\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- 첫번째 childNode의 nodeName : \" \r\n");
      out.write("\t\t\t\t\t+ nodeId.childNodes.item(0).nodeName + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- 첫번쨰 childNode의 nodeValue : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.childNodes.item(0).nodeValue;\r\n");
      out.write("\t\t\t\talert(msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\t\tvalue=\"id가 c, d, e인 노드(ByID)\"\r\n");
      out.write("\t\t\tonclick=\"id03()\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction id03() {\r\n");
      out.write("\t\t\tvar nodeId = document.getElementById(\"c\");\r\n");
      out.write("// \t\t\tc는 되지만 d, e는 안된다!!!!! id를 여러개 주면 안된다! 1개만줘!\r\n");
      out.write("\t\t\tvar msg = \"- id attr 값 : \" \r\n");
      out.write("\t\t\t\t\t+ nodeId.getAttribute(\"id\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- msg attr 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.hasAttribute(\"msg\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- data attr 유무 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.hasAttribute(\"data\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- msg attr 값 : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.getAttribute(\"msg\") + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- 첫번째 childNode의 nodeName : \" \r\n");
      out.write("\t\t\t\t\t+ nodeId.childNodes.item(0).nodeName + \"\\n\"\r\n");
      out.write("\t\t\t\t\t+ \"- 첫번쨰 childNode의 nodeValue : \"\r\n");
      out.write("\t\t\t\t\t+ nodeId.childNodes.item(0).nodeValue;\r\n");
      out.write("\t\t\t\talert(msg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t6. 설정 변경(id가 show인 대상의 attr 변경하기)\r\n");
      out.write("\t<input type=\"button\"\r\n");
      out.write("\t\t\tvalue=\"id가 show인 메시지O 숨기기\"\r\n");
      out.write("\t\t\tonclick=\"setHide()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction setHide() {\r\n");
      out.write("\t\t\tvar target = document.getElementById(\"show\");\r\n");
      out.write("\t\t\talert(\"현재 : \" + target.getAttribute(\"style\"));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttarget.setAttribute(\"style\", \"display:none\");\r\n");
      out.write("\t\t\talert(\"수정 후 : \" + target.getAttribute(\"style\"));\r\n");
      out.write("\t\t\t\r\n");
      out.write("// \t\t\t위의 명령은 다음과 같음\r\n");
      out.write("\t\t\ttarget.style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\r\n");
      out.write("\t문제 : div의 선 굵기와 색 바꾸기\r\n");
      out.write("\t<input type=\"button\" value=\"div style바꾸기\"\r\n");
      out.write("\t\t\tonclick=\"divChange()\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction divChange() {\r\n");
      out.write("\t\t\tvar targetDiv = document.getElementById(\"dixEx\");\r\n");
      out.write("// \t\t\ttargetDiv.setAttribute(\"style\", \"border: solid 5px red\");\r\n");
      out.write("\t\t\ttargetDiv.style.border = \"solid 6px blue\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
