/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-15 07:27:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class j26_005fjquery_005fstop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1486693217882L));
    _jspx_dependants.put("jar:file:/C:/Users/Yeob's/Desktop/eclipse/JSP_Works/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Curr11_Ajax_Jquery/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\"> <title>Insert title here</title>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("    \tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ min_js }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.a {\r\n");
      out.write("\t\t\tmargin-bottom: 50px;\r\n");
      out.write("\t\t\theight: 50px;\r\n");
      out.write("\t\t\twidth: 50px;\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tbackground: red;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<h2>1. stop(true, true) : \r\n");
      out.write("\t\t\t정지(있음), 현재 명령완료여부(완료상태로 바로이동 후 정지)</h2>\r\n");
      out.write("\t<a id=\"start1\">시작</a>\r\n");
      out.write("\t<a id=\"stop1\">정지실행</a>\r\n");
      out.write("\t<div id=\"box1\" class=\"a\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(\"#start1\").click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(\"#box1\").animate({left: 500}");
      out.write(")\r\n");
      out.write("\t\t\t\t\t\t\t.animate({top: 10, height: 100, width: 100}");
      out.write(")\r\n");
      out.write("\t\t\t\t\t\t\t.slideUp(");
      out.write(")\r\n");
      out.write("\t\t\t\t\t\t\t.slideDown(");
      out.write(")\r\n");
      out.write("\t\t\t\t\t\t\t.animate({left: 0}");
      out.write(")\r\n");
      out.write("\t\t\t\t\t\t\t.animate({height: 50, width: 50}");
      out.write(");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t\t$(\"#stop1\").click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(\"#box1\").stop(true, true);\t// 명령 끝쪽으로 바로 이동해서 완료시킨다!\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t============================================================\r\n");
      out.write("\t\r\n");
      out.write("\t<h2>2. stop(true, false) : 정지?, 현재 명령완료여부?\r\n");
      out.write("\t\t\t정지(있음), 현재 명령완료여부(현재 명령 진행상황 중 정지 후, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t정지된 명령 마저 실행 후,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t 정지했던 명령부터 다시 진행)</h2>\r\n");
      out.write("\t<a id=\"start2\">시작</a>\r\n");
      out.write("\t<a id=\"stop2\">정지실행</a>\r\n");
      out.write("\t<div id=\"box2\" class=\"a\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(\"#start2\").click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(\"#box2\").animate({left: 500}, 500)\r\n");
      out.write("\t\t\t\t\t\t\t.animate({top: 10, height: 100, width: 100}, 500)\r\n");
      out.write("\t\t\t\t\t\t\t.slideUp(500)\r\n");
      out.write("\t\t\t\t\t\t\t.slideDown(500)\r\n");
      out.write("\t\t\t\t\t\t\t.animate({left: 0}, 500)\r\n");
      out.write("\t\t\t\t\t\t\t.animate({height: 50, width: 50}, 500);\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t\t$(\"#stop2\").click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(\"#box2\").stop(true, false);\t// 명령 끝쪽으로 바로 이동해서 완료시킨다!\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t=====================================================\r\n");
      out.write("\t\r\n");
      out.write("\t<h2>3. stop(false, true) : 정지?, 현재 명령완료여부?</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t<a id=\"start3\">시작</a>\r\n");
      out.write("\t<a id=\"stop3\">정지실행</a>\r\n");
      out.write("\t<div id=\"box3\" class=\"a\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(\"#start3\").click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(\"#box3\").animate({left: 500}, 2000)\r\n");
      out.write("\t\t\t\t\t\t\t.animate({top: 10, height: 100, width: 100}, 2000)\r\n");
      out.write("\t\t\t\t\t\t\t.slideUp(2000)\r\n");
      out.write("\t\t\t\t\t\t\t.slideDown(2000)\r\n");
      out.write("\t\t\t\t\t\t\t.animate({left: 0}, 2000)\r\n");
      out.write("\t\t\t\t\t\t\t.animate({height: 50, width: 50}, 2000);\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t);\r\n");
      out.write("\t\t$(\"#stop3\").click(\r\n");
      out.write("\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t$(\"#box3\").stop(false, true);\t// 명령 끝쪽으로 바로 이동해서 완료시킨다!\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h2>4. stop(false, false) : 정지?, 현재 명령완료여부?</h2>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /j26_jquery_stop.jsp(8,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("min_js");
      // /j26_jquery_stop.jsp(8,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/j26_jquery_stop.jsp(8,1) '/Curr11_Ajax_Jquery/files_js/jquery-3.1.1.min.js'",_jsp_getExpressionFactory().createValueExpression("/Curr11_Ajax_Jquery/files_js/jquery-3.1.1.min.js",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    }
    return false;
  }
}
